### ISSUE TITLE
goo.gl backend issue

### ISSUE THREAD

**Issue by Epithumia** [owncloud/shorty#124]
It seems that with the changes to shorty in the 0.5.0 version, goo.gl support broke. I have the public API key set up (key configured in shorty, IP allowed on the google console, shortener API enabled), but trying to add a new shorty fails silently on the frontend, and spams the log file (it adds thousands of identical entries) in the admin page with lines such as:

Error 	shorty 	Failed to register url at backend 'goo.gl'. Error 0: 	2015-03-27T00:36:32+00:00 

Looking at the google console, I don't even see a hit, which would indicate shorty fails to even reach the "ask goo.gl for an url" part of the process.

**Comment by arkascha** [comment]
@Epithumia Thanks for the feedback! 
Looks like there is an endless loop, maybe caused by a redirection that Shorty does not understand. Could be a change on google's side. I will take a look into it!

**Comment by arkascha** [comment]
Fixed the exception raising in branch 'master' which was indeed broken and caused an endless loop. 
@Epithumia You wanna give it a try? Otherwise that change will be part of release 0.5.1.

**Comment by Epithumia** [comment]
Now it displays the error in a popup (see below), but still fails to register the shortlink (and the API console still shows no hit).
Error message:
```
Unexpected type of exception caught:OCA\Shorty\Exception)
Failed to register url at backend 'goo.gl'.
Error 0:
```
After that a progression circle appears and keeps turning, preventing clicking on all the shorties behind it. Using the refresh button makes it go away.

**Comment by Epithumia** [comment]
And I think I know why it fails to register.
Try this from a command line from a machine allowed by the API key:
```
curl -X POST -H "Content-Type: application/json" -d '{"longUrl": "www.google.fr", "key": "<your_api_key>"}' https://www.googleapis.com/urlshortener/v1/url
```
Results in 

```json
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```
Whereas this:
```
curl -X POST -H "Content-Type: application/json" -d '{"longUrl": "www.google.fr"}' https://www.googleapis.com/urlshortener/v1/url?key=<your_api_key>
```
Works and returns
```json
{
 "kind": "urlshortener#url",
 "id": "http://goo.gl/jgl7",
 "longUrl": "http://www.google.fr/"
}
```
lib/backend.php needs patching, code should be
```php
	$curl = curl_init ( );
curl_setopt ( $curl, CURLOPT_URL, 'https://www.googleapis.com/urlshortener/v1/url?key='.$api_key );
curl_setopt ( $curl, CURLOPT_SSL_VERIFYHOST, (\OCP\Config::getUserValue(\OCP\User::getUser(),'shorty','backend-ssl-verify')) );
curl_setopt ( $curl, CURLOPT_SSL_VERIFYPEER, (\OCP\Config::getUserValue(\OCP\User::getUser(),'shorty','backend-ssl-verify')) );
curl_setopt ( $curl, CURLOPT_POST, TRUE );
curl_setopt ( $curl, CURLOPT_HTTPHEADER, [ 'Content-Type: application/json' ] );
curl_setopt ( $curl, CURLOPT_POSTFIELDS, json_encode( [ 'longUrl'=>$relay]) );
curl_setopt ( $curl, CURLOPT_RETURNTRANSFER, TRUE );
```

**Comment by arkascha** [comment]
Indeed looks like google changed quite some details inside that API. Great idea to make backwards incompatible API changes... I mean why _do_ they have an API versioning?
Anyways, I get more issues after that, still trying....

**Comment by arkascha** [comment]
@Epithumia OK, sorted out the other issues. Appears to be working now, thanks for the hint.

**Comment by arkascha** [comment]
Closing this issue as "outdated and not getting updated".
